kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ${project.artifactId}
  namespace: ${ocp-namespace}
  labels:
    app: ${project.artifactId}
spec:
  strategy:
    type: Rolling
  replicas: 1
  template:
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 12
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          name: loyalty-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 12
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
